### ISSUE TITLE
maPointValue - enable-popup hard to keep open

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#104]
It was observed on a client's system that the popups on their ma-point-value items in their dashboards didn't stay open even when they mouse was hovering over the buttons in the popup.

After some experimenting, I believe this to be related to multiple ma-point-value elements having some overlap, but I don't know

**Comment by jazdw** [comment]
This is caused by the mouse moving over a tooltip. The tooltips are positioned correctly the first time they open but the second time they show they are in the wrong position due to a bug in Angular Material.

**Comment by jazdw** [comment]
Fixed via upgrading Angular Material library.
