### ISSUE TITLE
Json Import - Cancel Doesn't Stop Temp Resource Polling

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-dashboards#110]
@terrypacker wrote
> I was testing the new endpoint and found that if uploading many data points (1000+) via a file and then hitting cancel it does stop the backend import but it doesn't cancel the polling of the temporary resource.

**Comment by terrypacker** [comment]
Just tested this again and it is now working as expected.  Note that you need to have a large enough import to be able to cancel it while it is running.  1000 points works fine for this test.
