### ISSUE TITLE
Option to download PointValue Timestamps as Strings

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#112]
I've added some new URL parameters to the PointValueRestController:

String dateTimeFormat - Format passed to DateTimeFormatter
String timezone - timezone converted to ZoneID and used in formatting

Some endpoints had the timezone but now they all do.

Basically if you don't pass in a dateTimeFormat you get back numeric timestamps otherwise the format is validated and used to return Strings for csv and JSON output.

Can you add a drop down/text input box for choosing the format when downloading the files from the Watchlist export page.  

If desired we can look at making these files compatible with the Point Value Import for 3.3.0.  We could determine the String format needed for the import and add a button which generates a compatible file for Importing...

The format is in the example files in the Point Data Import module.  There is an XLSX format that we currently don't support exporting but we could with probably little effort.

**Comment by jazdw** [comment]
@terrypacker Thats added, only two options for date format - ISO or Epoch. For ISO I am using the format string "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"

We should also add support to the REST API to use java.time.format.FormatStyle so we get locale aware formats for FULL/LONG/MEDIUM/SHORT.
