### ISSUE TITLE
Modules Page - Download Errors are Slient

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#125]
I found when I get a download error from the store, the information is stored in the ModulesDwr and thus should be retrieved via a status call to the rest endpoint, but nothing ever happens in terms of feedback on the page.

See lines 472-477 in ModulesDwr for what status is set.

**Comment by terrypacker** [comment]
I've worked out the problem, its the new web socket.

We will need to fix up the backend instead of the frontend I presume.

**Comment by jazdw** [comment]
Closed in 92c4fe15106bb448f4ce9990d80bce55679b81b3
