### ISSUE TITLE
Logout-login

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#139]
If the admin user logs out, and then immediately attempts to log back in, his first request on the /ui/login page will get bounced because the CSRF isn't registered or some such.

**Comment by jazdw** [comment]
I saw this happen the other day. I can generate the XSRF cookie client side to fix this.

**Comment by jazdw** [comment]
The reason this is hard to reproduce is because anytime a network request to Mango occurs the XSRF cookie will be set, you can only reproduce this is you

1. Haven't visited the login page
2. Login within 10 seconds of being on the login page (theres a periodic network request to the Mango server)
