### ISSUE TITLE
Excel Reports, cannot save upon modifying

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#157]
I created a very simple report with a single time range and one point in it. I saved the report. then opened it back up to edit it again. I was able to edit things, but the save button remained disabled no matter what I changed.

**Comment by Puckfist** [comment]
@guetteluis this is probably something for you to look at

**Comment by Puckfist** [comment]
The delete button also seems permanently disabled

**Comment by Puckfist** [comment]
The only way I can get the buttons to enable is deleting all the time ranges

**Comment by guetteman** [comment]
Ok, I'm going to check that. Thanks
