### ISSUE TITLE
UI Pages missing items

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#162]
Ways to make items disappear from the JSON store list of UI pages,

Setup: a nonadmin user needs permission to edit the UI pages item

1. If a page exists in the list of UI pages that the lower privilege user cannot read or edit, loading the Edit pages page is sufficient to remove it from the UI Pages
2. If they have permission to a menu item that links to a page that they do not have permission on and they attempt to visit it.

Ways to get the set of pages in the JSON store out of sync with the UI pages list

1. If the initial save of the JSON store is taken, but the response times out or the tab is immediately closed.

**Comment by jazdw** [comment]
Fixed main issue in 72371fb445c808cb5dc6cde01d7b52a842e3f45d

Thanks @Puckfist
