### ISSUE TITLE
Excel Reports Table - View Record Count

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#184]
This is mostly for discussion but I was testing Excel Reports and found that my report had no data in it, however this is not shown on the run reports table/view.  This info is in the model and would probably be good to display in a column.

**Comment by jazdw** [comment]
What does "no data" mean? What model properties are we talking about here?

**Comment by terrypacker** [comment]
"no data" means no point values at all were returned in the query for the time range and points I had selected.  The model property is `recordCount` in the ExcelReportModel

**Comment by terrypacker** [comment]
@guetteluis again when you start working on ExcelReports this one should be on your list.
