### ISSUE TITLE
Event detector and data point popups quite willing to close

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#193]
Almost every other page notices that you haven't saved. But, neither the data points nor event detector popups hesitate to close.

Was this purposeful?

**Comment by jazdw** [comment]
Kind of, I think we overdid the popups requiring confirmation to discard changes.

@Joelhaggar @terrypacker Care to chime in and comment? Where do you think it is necessary to confirm to discard changes?

**Comment by terrypacker** [comment]
I can see their usefulness but I definitely don't like having to click a button when I restart Mango and I was on an edit page before it shows the login page.
