### ISSUE TITLE
Event handler names were not always required - event detector popup

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#194]
If one has an event handler from the past, its 'alias' field was not required. Now it is required that an EH have a name, but old handlers appear in the event detector list (if unaliased originally) as blank space:

![no-handler-name](https://user-images.githubusercontent.com/4428029/55351747-5594be00-547c-11e9-91fe-0f0d6b91991c.png)

Perhaps it should say the handler type as the old page did? Maybe that with the XID? Or, maybe something like that should autogenerate the name field during the upgrade?

**Comment by jazdw** [comment]
Sounds like a job for an upgrade script, I assume the DB column is not marked as "non-null" either.

**Comment by terrypacker** [comment]
This is done via upgrade script and the new name is type description - XID.  I also marked the alias column in the DB to be not null
