### ISSUE TITLE
Edit multiple data points, chart renderer tab has issue

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#197]
Typically when editing multiple points <<multiple values (n)>> seems displayed in fields where the points don't already have the same setting. With the chart renderer tab, however, I am seeing the selector for chart renderer type disabled with that value when they do not have the same chart renderer, but blank and disabled when they do:

![chart-renderer-disabled](https://user-images.githubusercontent.com/4428029/55498982-1e501980-5602-11e9-9c91-834292031caa.png)

**Comment by jazdw** [comment]
I cant reproduce this. Judging by your picture you are trying to edit two numeric data points which both currently have a statistics chart renderer?

**Comment by Craig-IAS** [comment]
If I select a Binary point and an alphanumeric point, click edit and try to change their device name.  I cannot save. The chart renderer type is disabled and empty so the form validation does not allow you to save.
![untitled (4)](https://user-images.githubusercontent.com/47353996/55556443-e4594300-56e7-11e9-8401-64274997d670.png)

**Comment by jazdw** [comment]
Thanks @Craig-IAS that helped identify it.
