### ISSUE TITLE
Data sources page, newly created source not in list of sources?

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#198]
Seems to be a half-sized screen issue only, although I noticed at full size it adds to the end of the list instead of resorting it. I create a new source, save it, the drop down to select the source is blank and it is not present in the list:

![no-source-selected](https://user-images.githubusercontent.com/4428029/55500785-388bf680-5606-11e9-891a-1e9d70bfd3cc.png)
![not-in-list](https://user-images.githubusercontent.com/4428029/55500787-388bf680-5606-11e9-8dec-aa8384d78be2.png)

**Comment by jazdw** [comment]
Yeah caused by an the old select component not getting WebSocket updates
