### ISSUE TITLE
Adding BACnet points via the scan tool doesn't allow have selection for name field

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-dashboards#201]
On the legacy UI for BACnet you can select to use the Object Name or Description as the Mango Data Point name.  This is not available in the new UI scan tool and looks like it is defaulting to use the Description.

In this example, the device has a Name and Description but most of the points get populated with "Default Bacnet Description" as their name
![image](https://user-images.githubusercontent.com/2327703/55651606-65770f80-57a6-11e9-82b0-d67a87dc0927.png)

This device populates the Mango names correctly:
![image](https://user-images.githubusercontent.com/2327703/55651715-c56db600-57a6-11e9-8645-cd6346765ba7.png)

**Comment by jazdw** [comment]
Yeah I was considering just making it add both the name and description as tags. It currently uses the description if it is not empty and falls back to the name.

"Default Bacnet Description" must be coming from either the BACnet4J library or the device itself. Its not something in the UI.

**Comment by terrypacker** [comment]
"Default Bacnet Description" would be coming from the device you are exploring that is simply passed through from the message received in BACnet4J --> REST API --> UI

**Comment by jazdw** [comment]
Closed via infiniteautomation/ma-modules-private@c96d468a7d79fb50baf22d0365bea47e0526b7c5
