### ISSUE TITLE
Bulk data point editor: display message if point has a Template

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#203]
We need to display a message when editing a point with a template applied.  Ideally we will also disable/hide the inputs that are affected by the template being applied upon save.

**Comment by jazdw** [comment]
@terrypacker I thought the consensus was to remove the template upon save?

**Comment by terrypacker** [comment]
@jazdw you are correct but I think we also decided to show a message if you start editing a point or points that have templates applied so that it is obvious that they will be removed.

**Comment by jazdw** [comment]
![image](https://user-images.githubusercontent.com/3579645/55836769-b8b9cc80-5adc-11e9-953a-b72f5430583a.png)

**Comment by Joelhaggar** [comment]
I wonder if we should update this page and give a link to is so they can learn about what a Data Point template is https://help.infiniteautomation.com/using-data-point-templates or maybe there is a help page in Mango we can use for this.  I think many users might not know what this is as using a template was the default when saving a data point in the past.

**Comment by terrypacker** [comment]
There is a 20 line help file at WEB-INF/dox/dataPointTemplate.htm in the core.

**Comment by jazdw** [comment]
@Joelhaggar @terrypacker Please check help content and edit it if necessary https://github.com/infiniteautomation/ma-dashboards/blob/main/UI/web-src/ui/views/help/dataPointTemplate.html

**Comment by terrypacker** [comment]
@jazdw we have both reviewed it and it is fine.  Thanks.
