### ISSUE TITLE
Controller 'ngModel', required by directive 'maFlattenValues', can't be found!

### ISSUE THREAD

**Issue by Craig-IAS** [infiniteautomation/ma-dashboards#204]
**Describe the bug**

when editing multiple multi-state data points that belong to a virtual data source. I get the following error in chromes console:  [$compile:ctreq] Controller 'ngModel', required by directive 'maFlattenValues', can't be found!

**To Reproduce**

Select more than one data point that is type multistate and edit them. 

**Expected behaviour**
No error

**Screenshots**
![untitled (6)](https://user-images.githubusercontent.com/47353996/55800618-6d032500-5ad4-11e9-9b56-2e01a824b8ee.png)

**Mango Version (please complete the following information):**
 - Core Version: 3.6.0-beta.1

**Browser (please complete the following information):**
 - Device: Laptop
 - OS: ubuntu 18.04 LTS
 - Name [chrome]
 - Version Version 70.0.3538.77

**Comment by jazdw** [comment]
Thanks @Craig-IAS good catch.

@guetteluis You should not use `ma-flatten-values` on an input without `ng-model`
