### ISSUE TITLE
Meta point script does not validate if using the point's own variable

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-dashboards#207]
Meta point script does not validate if using the point's own variable. See screenshot. I assume this is because its not added to the array of context points when sending it to the validation endpoint. Please test with a new data point and when updating an existing data point.

![image](https://user-images.githubusercontent.com/3579645/55893641-f159b480-5b75-11e9-9759-121e2a3576f3.png)

**Comment by guetteluis** [comment]
When the data point is new, I disabled the Validate button and added a warn message at the top of the script editor. What do you think @jazdw ?
<img width="1080" alt="Screen Shot 2019-04-10 at 5 32 17 PM" src="https://user-images.githubusercontent.com/35845741/55915076-bdeb4a00-5bb6-11e9-841a-9a8add1a341c.png">

**Comment by jazdw** [comment]
@guetteluis Please reference the commit so I can see what you changed.

**Comment by guetteluis** [comment]
I added a `disable-validation` property for scripting editor component in https://github.com/infiniteautomation/ma-dashboards/commit/6e40afc4809a510d12800d41e1b7e787106578d4 and added the `saveFirst` message in https://github.com/infiniteautomation/ma-modules-private/commit/7e68989e20c33a9b13d5459f11eedc773e968e67

**Comment by guetteluis** [comment]
I added a `disable-validation` property for scripting editor component in https://github.com/infiniteautomation/ma-dashboards/commit/6e40afc4809a510d12800d41e1b7e787106578d4 and added the `saveFirst` message in https://github.com/infiniteautomation/ma-modules-private/commit/7e68989e20c33a9b13d5459f11eedc773e968e67

**Comment by guetteluis** [comment]
I added a `disable-validation` property for scripting editor component in https://github.com/infiniteautomation/ma-dashboards/commit/6e40afc4809a510d12800d41e1b7e787106578d4 and added the `saveFirst` message in https://github.com/infiniteautomation/ma-modules-private/commit/7e68989e20c33a9b13d5459f11eedc773e968e67

**Comment by guetteluis** [comment]
I added a `disable-validation` property for scripting editor component in https://github.com/infiniteautomation/ma-dashboards/commit/6e40afc4809a510d12800d41e1b7e787106578d4 and added the `saveFirst` message in https://github.com/infiniteautomation/ma-modules-private/commit/7e68989e20c33a9b13d5459f11eedc773e968e67

**Comment by guetteluis** [comment]
I added a `disable-validation` property for scripting editor component in https://github.com/infiniteautomation/ma-dashboards/commit/6e40afc4809a510d12800d41e1b7e787106578d4 and added the `saveFirst` message in https://github.com/infiniteautomation/ma-modules-private/commit/7e68989e20c33a9b13d5459f11eedc773e968e67

**Comment by guetteluis** [comment]
I added a `disable-validation` property for scripting editor component in https://github.com/infiniteautomation/ma-dashboards/commit/6e40afc4809a510d12800d41e1b7e787106578d4 and added the `saveFirst` message in https://github.com/infiniteautomation/ma-modules-private/commit/7e68989e20c33a9b13d5459f11eedc773e968e67

**Comment by guetteluis** [comment]
I added a `disable-validation` property for scripting editor component in https://github.com/infiniteautomation/ma-dashboards/commit/6e40afc4809a510d12800d41e1b7e787106578d4 and added the `saveFirst` message in https://github.com/infiniteautomation/ma-modules-private/commit/7e68989e20c33a9b13d5459f11eedc773e968e67

**Comment by jazdw** [comment]
OK looks good please create PRs.

**Comment by terrypacker** [comment]
@guetteluis I am currently editing a previously saved point and getting this error:

```
'ReferenceError: "my" is not defined' on line 1
ReferenceError: "my" is not defined
```

Please ensure that the editing point is added to the array of context points.  I have not tested this on your branch but neither of the commits referenced above will fix what I am seeing.
