### ISSUE TITLE
ma-scripting-editor does not display some validation errors

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-dashboards#208]
If the result from a validation does not include a line/col number the ma-scripting-editor does not display the error.

Example output from REST API
![image](https://user-images.githubusercontent.com/3579645/55898580-223ee700-5b80-11e9-9c01-67d4d48767ff.png)

**Comment by guetteluis** [comment]
@jazdw can you provideme the script example so I can test?

**Comment by jazdw** [comment]
This should do the trick, you need to have superadmin in your script roles.
```
var address = java.net.InetAddress.getByName("10.55.55.10/24");
```

**Comment by guetteluis** [comment]
fixed in https://github.com/infiniteautomation/ma-dashboards/commit/749a0d58b6251884e1ced8f6fedc09ba284f5c19
