### ISSUE TITLE
JSON Import does not update Editing Data Source

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#210]
I opened a data source for editing and then imported a configuration for it that had a change, this change did not show up until I selected a different data source for editing and then re-selected the one I imported.

If it matters this was a Scripting data source and I modified the Script Permissions.

**Comment by jazdw** [comment]
Seems to be the expected behavior to me. Imagine you are in the middle of editing a data point, do you want your changes to be overridden every time someone else edits the point elsewhere? This can only be solved if we include a version/timestamp column in the DB for each VO object.
