### ISSUE TITLE
JSON import does not update editing data point

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#211]
While editing a meta data point I imported a configuration with new script permissions.  This was not reflected in the UI until I closed and re-opened the edit view for that point.

**Comment by jazdw** [comment]
Seems to be the expected behavior to me. Imagine you are in the middle of editing a data point, do you want your changes to be overridden every time someone else edits the point elsewhere? This can only be solved if we include a version/timestamp column in the DB for each VO object.
