### ISSUE TITLE
Excel Report Template - No error displayed when template file DNE

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#214]
I was trying to edit an Excel Report Template that I imported but the excel template file was not brought across.  The page does nothing but the log output is:

```
DEBUG 2019-04-11T10:13:36,457 (com.infiniteautomation.mango.rest.v2.exception.RestExceptionHandler.handleExceptionInternal:184) - Rest API Exception 
com.infiniteautomation.mango.rest.v2.exception.GenericRestException: Report template file not found
```

**Comment by jazdw** [comment]
@terrypacker please check the REST response and let me know what the REST response contains.

**Comment by terrypacker** [comment]
![image](https://user-images.githubusercontent.com/3905204/56005045-2fd09b80-5c6a-11e9-8b47-af8767b8be26.png)

The JSON payload is:
```
{
  "cause" : null,
  "mangoStatusCode" : -1,
  "mangoStatusName" : null,
  "localizedMessage" : "Report template file not found"
}
```

**Comment by terrypacker** [comment]
I could make the response a 404 but that is a little ambiguous if you don't look at the message as the actual template VO may not exist.

**Comment by terrypacker** [comment]
@guetteluis when you start working on Excel Reports I'd like to fix this one up too.

**Comment by guetteluis** [comment]
Hey @terrypacker can you explain me more about how do you get this error? Thanks

**Comment by terrypacker** [comment]
@guetteluis you should create an Excel Report Template then go to the file store where the template is and delete the file.  Then try to open the template and edit it.
