### ISSUE TITLE
Event handler tree of handled events not properly open if events are selected when loaded

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#217]
To reproduce, save an event handler that handles an event, then refresh the page and select that event handler and navigate to the Event Types tab. The events that it handles will have the carrot in the row suggesting the group is expanded, but it is not, and it take two clicks on the carrot to expand it

**Comment by terrypacker** [comment]
I have reproduced this using the above description.  See the 1`Dashboard Demo - Disabled (1 Selected)` row in this image:

![image](https://user-images.githubusercontent.com/3905204/57491743-afe22500-7259-11e9-8fa7-6a478c3b36ea.png)
