### ISSUE TITLE
Watchlist Builder - Validation message for Name not working

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#222]
When creating a new watchlist if you leave the Name input empty and go through all the steps and then try to save it.  You are redirected back to the page with the Name input but the field is not highlighted.

No REST call is made so this must be happening in the validation on the page.

**Comment by jazdw** [comment]
Also cannot replicate this one. Will need more details.

**Comment by jazdw** [comment]
Only occurs when using the bottom save button.
