### ISSUE TITLE
Watchlist created by builder doesn't let me set point values?

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#223]
I created a new watchlist via the builder but when I select it and hover over a point I don't see the set value icon.  I can see the icon if I change to the Devices or Sources view but not via my list.

Is this a bug or am I missing something?

**Comment by jazdw** [comment]
I can't replicate. Please ensure you are looking at the same data point and it is settable. If it still doesn't work then please include more details about the type of watch list and what the query contains etc.

**Comment by jazdw** [comment]
Found to be an issue with the point locators being missing when getting points for a static watch list.
