### ISSUE TITLE
Modbus Read Data Tools

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#227]
We need a tool in the new UI that can read data for a specific set of registers.  

The endpoints are at:

`v2/modbus/serial/read`
`v2/modbus/ip/read` 

I'm assuming we want to get back values and not raw data however it may be nice to have the option to get back the data as it exists in the registers.  This can be done via these endpoints:

`v2/modbus/serial/read-raw`
`v2/modbus/ip/read-raw`

Note that this is different than the Locator Read Tool as this reads raw data, the locator tool will read data and convert it to Mango data types.

**Comment by jazdw** [comment]
Done.
