### ISSUE TITLE
Modbus Write Data Tools

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#228]
We need a data source tool to write data into Modbus registers.

The endpoints are at:

`v2/modbus/serial/write`  
`v2/modbus/ip/write`

I'm assuming we want to write typed values and not raw data however it may be nice to have the option to write raw short[] data into the registers. This can be done via these endpoints:

`v2/modbus/serial/write-raw`  
`v2/modbus/ip/write-raw`

**Comment by jazdw** [comment]
Done, only supports writing single registers at a time, raw writes can be done via selecting unsigned 16 bit int.
