### ISSUE TITLE
Modbus Test Locator Tools

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#229]
We need data source tools to test the settings of a point locator before it is saved.  This can be done by doing a test read using the point locator settings via this endpoint:

`v2/modbus/serial/locator`
`v2/modbus/ip/locator`

**Comment by jazdw** [comment]
Kind of done, does not use those end points, it provides the ability to read the modbus data as a particular type (e.g. 32 bit float etc) but does not allow you to set multipliers etc. @Joelhaggar try it out and see if it makes sense.
