### ISSUE TITLE
BACnet IP Local Device - Add reuse address checkbox

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#233]
Add Reuse address checkbox to BACnetIP Local device configuration.

The property in the model is reuseAddress: true/false

**Comment by guetteluis** [comment]
added checkbox here: https://github.com/infiniteautomation/ma-modules-private/commit/d53122afbfe43bee368abb496988f166c3a44537

BTW this should be in `ma-modules-private` repo
