### ISSUE TITLE
Ability to limit what is in the points list drop down

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#235]
There are several use cases where we don't want to be able to select points from a drop down.

1.  As a meta point you should not be able to add yourself as a context point
2. Once a point is added to a script context it should not appear in the list of available points to add.
3. When adding a point to a publisher it should disappear from the list of available points

When this is complete we need to open new issues for @guetteluis to leverage this feature for all Script Context point inputs.

**Comment by jazdw** [comment]
@guetteluis @terrypacker Here is an example, you can pass an array of data points or xids to the `filter-points` attribute.

```
<div class="ma-designer-root" id="089aff1e-c208-4ef5-995e-bd7a6a8e979f" style="width: 1366px; height: 768px; position: relative;" ng-init="page = {points: []}">
    <ma-filtering-point-list id="9cceb2c9-9775-46f3-b4a6-fa2931cf73a7" ng-model="page.dp" get-by-xid="true" style="position: absolute; left: 92px; top: 51px; width: 384px;" ng-change="page.points.push(page.dp); page.dp = null;" filter-points="page.points" filter-expression="$point.name !== 'Poll duration'"></ma-filtering-point-list>
    <div id="656dbad8-9c56-4e15-8b02-e708c668cb8e" style="position: absolute; left: 33px; top: 147px; width: 808px; height: 442px; overflow-y: scroll;">
        <div ng-repeat="point in page.points track by point.xid">
            <span ng-bind="point.name"></span>&nbsp;<md-icon ng-click="page.points.splice($index, 1)">delete</md-icon>
        </div>
        
    </div>
</div>
```
