### ISSUE TITLE
New tags don't show up in bulk editor

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#237]
I was testing a brand new system with 0 tags in it.  I added a tag but it didn't show up in the 'Select tags' drop down until I refreshed the page.

Steps:
 1. I went to the bulk editor, selected Devices
2.  Select 1 point for editing
3.  Add tag to that point and save
4.  Returned to bulk editor and no new tag in drop down

This seems to be the same whether there are pre-existing tags in the system or not.

**Comment by jazdw** [comment]
Screenshot please. I don't know which "Select tags" drop down you are referring to. To confirm, you are talking about 3.6.0 yes?

**Comment by terrypacker** [comment]
Yes Mango 3.6.0 latest build.

![image](https://user-images.githubusercontent.com/3905204/56919118-78a29580-6a5b-11e9-865e-e755e4a1054e.png)

**Comment by terrypacker** [comment]
The test tag drop down in the upper right of that screenshot.  It doesn't obtain the new tags until the page is refreshed.
