### ISSUE TITLE
Closing Data Point Purge modal causes REST exception

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#243]
When testing purging point values I found that an Exception is being thrown by the REST api when the UI tries to cancel an already completed purge.  

To reproduce:

1. Edit a data source
2. Select a point (check its box)
3. Click the purge trashcan
4. Check purge all data for selected point
5.  Click PURGE POINT VALUES
6.  Click the x to close it after the purge finishes

See the DEBUG message in the backend as a PUT to v2/point-values/purge/{id} is made to cancel the resource but its already completed.

![image](https://user-images.githubusercontent.com/3905204/57172093-2c3abb00-6db7-11e9-970d-c883ee6c9dc3.png)

**Comment by terrypacker** [comment]
@pierpuccini see if this is still happening.

**Comment by pierpuccini** [comment]
No errors occuring in debug console, and mentioned PUT request is now a POST.
