### ISSUE TITLE
Retain filter text when adding data points via ma-filtering-point-list

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#247]
In the legacy UI on things like Meta Data context points and publisher points there is a hack to allow the drop down to remain open so that one can quickly and easily add multiple points.  Something similar would be nice to have in the new UI.

For example when filtering using text and adding a data point to a Meta Data point context the filter text goes away after adding the point so I have to filter the list again to add points.

**Comment by jazdw** [comment]
Now uses a new data point selector component.
