### ISSUE TITLE
Script Context translation missing for Script Editor

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#249]
The translation for dsEdit.script.scriptContext is not working on the Email Event Handlers page:

![image](https://user-images.githubusercontent.com/3905204/57335697-1ed74680-70bf-11e9-850c-d612c34ec4ea.png)

My guess is that since it is in a different namespace it isn't getting loaded.  I would suggest you add that to the scriptingEditor namespace AND potentially rework those translations to start with `ui.`

I'll let @jazdw weigh in on that one if my suspicions are correct.

**Comment by jazdw** [comment]
@terrypacker yes, you are correct that this is why it is occurring.
