### ISSUE TITLE
UI URL Paths are not backwards compatible. 

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#250]
While testing the demo site with the latest Mango 3.6 Snapshot I found a custom page that linked to excel reports like this `/ui/administration/excel-reports` which causes a page not found response.  It seems the now-correct URL is `/ui/administration/excel-reports/`.

I can make to guarantees that it was correct before the upgrade as I didn't test the custom page it or know it existed.

**Comment by jazdw** [comment]
URL has always had a `/` on the end. You should not link to this page using a `href` attribute, you should use `ui-sref` to link to the state.
