### ISSUE TITLE
PublicUrl == PrivateUrl --> Can't start Mango

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#26]
Because the URI handlers are dynamically mapped, and a runtime exception is thrown if two handlers attempt to map to the same endpoint at startup, it is possible to set these values equal to one another and prevent Mango from starting!

It looks like the fix may be validating this in the JavaScript, since the SystemSettingsDwr handles the actual saving.

**Comment by jazdw** [comment]
I vote for removing the public/private URL mapping things, we don't really use these any more.

**Comment by jazdw** [comment]
Closing as wont fix, I'm going to remove these in the upcoming UI module.
