### ISSUE TITLE
Virtual Serial Port - add inputs for ip white list

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#261]
The backend supports adding a list of ip addresses that can connect to the open port of a Virtual Serial Port (Server Socket) but there are no inputs in the UI for this.

Add the inputs and help to the system settings section.

The the model/backend has all the validation and getter/setter implementation.

```
{ ...
    ipWhiteList: [String, String, ... ],
```

**Comment by guetteluis** [comment]
@terrypacker I have added the IP white list input, but I don't see the parameter in the model from the backend. I have updated `mangoAPI` and the `core`.

**Comment by terrypacker** [comment]
They definitely are there.  This is only available on the Serial Server Socket Bridge:

![image](https://user-images.githubusercontent.com/3905204/63296818-352f9980-c28d-11e9-984a-6560e9442c93.png)

**Comment by jazdw** [comment]
@guetteluis Any updates on this?

**Comment by luisguette** [comment]
@jazdw I haven't had time, but I can work on these issues tomorrow.

**Comment by terrypacker** [comment]
@pierpuccini can you test and confirm this is working.  Basically add a few whitelisted IPs and then confirm they are saved and reloaded in the UI

**Comment by pierpuccini** [comment]
Is this how the test should appear? If it is, I added my own IP, saved, refreshed and it appeared.

![image](https://user-images.githubusercontent.com/46226655/75598958-53f9be80-5a6e-11ea-96f5-91d0b23b2dee.png)
