### ISSUE TITLE
Dashboards - Already logged in, login again

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#27]
The behavior of the /dashboards/login page is such that even if you are logged in you can load the page and login again. If you have any legacy pages opened, these will break, creating NPEs in various places.

Also, the "Password" text that appears in the password box seems to stay in that box if the browser or a plugin auto-fills the field.

**Comment by jazdw** [comment]
The dashboards login works fine with the latest core.

2nd issue is a wont fix, that's a minor issue with the angular material library.
