### ISSUE TITLE
Double slash in statistics request on point details page.

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#279]
Just saw this request get made when changing the date bar for my point:

`
/rest/v2/point-values//statistics/DP_a8bf95be-37c0-4752-9a3a-bf49f1411af5?fields=VALUE&fields=RENDERED&fields=TIMESTAMP&fields=ANNOTATION&from=2019-07-04T21:46:22.360Z&to=2019-07-11T21:46:22.360Z
`

Note the double slash before statistics.  The Strict HTTP firewall will not allow these through I believe.

**Comment by terrypacker** [comment]
Saw the same thing on the watchlist page, probably a bug in the point value angular service logic.

**Comment by jazdw** [comment]
Noticed this independently and fixed it via 5cff3487b0b838c46b70c8a313c27585a2ea538f
