### ISSUE TITLE
Data Point Details - filtering "deviceName - name"

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#29]
I observed on the new Data Point Details page that if I selected a point, in my case "vrt - brown" I would get this selected. Then, if I tried to move to "vrt - brown2", it wouldn't show up in the list! This is because it is searching for either the deviceName or the name, but is not searching for the extended name.

**Comment by jazdw** [comment]
I've fixed this up but bear in mind that the separator is now a &mdash; not a hyphen.
