### ISSUE TITLE
Filter users on disabled

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-dashboards#292]
Add the ability to filter users by whether they are disabled.

@Joelhaggar any other fields we need to filter on?

**Comment by terrypacker** [comment]
@jazdw probably should add this as an option for the filter columns in the new User UI.

**Comment by Joelhaggar** [comment]
I think we should be able to filter on everything possible. Organization, name, email, phone, username, role, etc.

**Comment by jazdw** [comment]
Closed via 97342a8ed46b53b8b4aebbfc42a5845d49d147f9

Users page is now a table similar to the new data point selector where you can filter on every column.
