### ISSUE TITLE
Event handler page not showing all point event detectors.

### ISSUE THREAD

**Issue by Craig-IAS** [infiniteautomation/ma-dashboards#300]
Bug:
The event types tab on the event handler page does not display all the point event detectors on the system.  I have a system with 262 point event detectors.  I can only about the first 100 ED's in alphabetical order.   

Enhancement:
Listing event detectors by type on systems with large amounts of ED's is not ideal.  One would want to be able to filter by either data source or data point tags.

**Comment by jazdw** [comment]
Fixed via a678b9d5a64f1f59b05dbcb796574b1cf08c1708
