### ISSUE TITLE
CRON pattern for history sync is not getting saved on the PTCP publisher.

### ISSUE THREAD

**Issue by Joelhaggar** [infiniteautomation/ma-dashboards#303]
I set the CRON twice and saved and each time I go back to the publisher it is blank and no history syncs are being done.

**Comment by Craig-IAS** [comment]
Yes, I also noticed this today, as well as the encryption key. When saved on the new UI do not appear on the old UI

**Comment by terrypacker** [comment]
@Joelhaggar I can reproduce this and will look into it, likely a REST model bug.  
@Craig-IAS I cannot reproduce this.  Be more specific what is the "encryption key"  We have  `Shared key` and `Authorization key` as settings.  Either way both of those seem to be fine.  You may need to add screenshots as it may depend on other settings.

**Comment by terrypacker** [comment]
![image](https://user-images.githubusercontent.com/3905204/67106218-15035480-f1c2-11e9-9752-4d97b292649a.png)
@jazdw it looks like the `syncPattern` field is not being set for the PUT/POST.  I checked the UI code and didn't see why that doesn't work so I'll leave this with you.

**Comment by Craig-IAS** [comment]
@jazdw I can't reproduce it now either, I must have been confusing myself earlier.
