### ISSUE TITLE
Change behavior for data source performance page

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#316]
I see that the page makes these queries: 

```
data-points?match(name,*Consecutive%20run%20polls*)&sort(deviceName,name)&limit(20,0)
data-points?match(name,*Poll%20duration*)&sort(deviceName,name)&limit(20,0)
data-points?match(name,*Poll%20success%20percentage*)&sort(deviceName,name)&limit(20,0)
```

Which means you have to name the points correctly to see them on this page.  Ideally we could query for points using the attribute name and the Internal data source type.  Currently that isn't supported via REST.

**Comment by jazdw** [comment]
Re-open when supported by REST. Personally don't see much benefit from doing this.
