### ISSUE TITLE
Make log's filterable on Logging console page

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#319]
This page `/ui/administration/system-status/logging-console` should have a filter on the table to be able to search for a log file.

We could either add some RQL functionality to the endpoint or ideally just filter on the page.

**Comment by jazdw** [comment]
Closed via ab3c7dc85d512e7b0288042236ca10927e81aa40 and e75ee593b665c8e4152b5b01eddea2b5de84c487

**Comment by jazdw** [comment]
![image](https://user-images.githubusercontent.com/3579645/75849640-6e9ab180-5e39-11ea-92dd-9e4a7a7b755f.png)
![image](https://user-images.githubusercontent.com/3579645/75849672-8bcf8000-5e39-11ea-9ed0-0f042cf56858.png)
