### ISSUE TITLE
Permission error occurring in datapoint editor

### ISSUE THREAD

**Issue by pierpuccini** [infiniteautomation/ma-dashboards#338]
When the datapoint editor loads for the first time, saves and opens up after save, the following error occurs: ```TypeError: this.ngModelCtrl.$viewValue.split is not a function```

see screenshot bellow for more info

<img width="655" alt="Screen Shot 2020-04-29 at 4 00 14 PM" src="https://user-images.githubusercontent.com/46226655/80646529-84d87e80-8a32-11ea-9bd7-c3f2b99524f2.png">

**Comment by jazdw** [comment]
No longer valid, inputs have all been updated now.
