### ISSUE TITLE
Data Source Edit - Lazy load data points

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#342]
This is for the situation where you have thousands of points on a data source.

**Comment by jazdw** [comment]
Need metrics
- How long did the request take? Too long?
- Did the browser crash?
- How many data points did you have on the data source?

It was done this way for the bulk data point editing.

**Comment by terrypacker** [comment]
Moved to Jira: https://radixiot.atlassian.net/browse/RAD-1025
