### ISSUE TITLE
Publisher table bug - deleting publisher does not remove it from the list

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#348]
Starting with 0 publishers add 1 then try to remove it.  Still in list but gone from backend on refresh.  The same thing happens if I create 2 and then try to delete them.  Not sure if this is specific to PersistentTCP or not but that is what I tested with.

**Comment by pierpuccini** [comment]
@terrypacker  I created all other types of publishers and they deleted as they should have, the only one I couldn't test is the bacnet one

**Comment by jazdw** [comment]
@terrypacker It is likely a WebSocket issue, please test again and monitor your WebSocket to ensure the message gets delivered.

**Comment by pierpuccini** [comment]
@terrypacker when monitoring the WebSocket, I don't get the notification for when the persistent TCP is deleted.

**Comment by terrypacker** [comment]
Thanks guys, was a dao bug and is fixed.
