### ISSUE TITLE
Edit page - Cannot save menu item twice

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#35]
If one is editing a custom page, and uses the "Add/Edit Menu Item" button it will save the first time (although it seems to have hidden other custom menu items when I did that save, the template url item in my last issue #34 Edit: ah, moved it to bottom of the list) but you cannot use the dialog to change the menu item a second time... you have to navigate back to this page first.

**Comment by jazdw** [comment]
Fixed via c41c3712993c232da9181f40d415a9426d0934a2
