### ISSUE TITLE
Corrupted toast messages - not sure why

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#353]
I'm randomly seeing the toast event messages get corrupted upon display.  I can't rule out that is an issue with the actual message from the backend but I've seen this on multiple pages now.  I'm using a dev config that generates a lot of alarms which is probably why I see it semi-regularly.  I should also note that the message is always the same content as in the attached image.

Previously I thought it was only during or right after a JSON config import but today I saw it while attempting to login:

![image](https://user-images.githubusercontent.com/3905204/89673634-64fef500-d882-11ea-94de-64df789a7387.png)

**Comment by jazdw** [comment]
See #270
