### ISSUE TITLE
Make view script log file link able to be opened in new tab/window. 

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#356]
This button doesn't allow you to open it in a new window which is painful:

![image](https://user-images.githubusercontent.com/3905204/91366445-6e9fbc80-e79f-11ea-8fc4-a1af69174cca.png)

This would apply to anywhere this is used, I assume it is a component but could be wrong.

**Comment by jazdw** [comment]
Where is this? Meta point?

**Comment by terrypacker** [comment]
Yes this is a meta point but would be the same for Scripting data sources and Email/Set Point event handlers I believe.

I also just noticed the link is wrong too:  My meta point is id 68 but the link takes me to: `...\logging-console?filenameFilter=metaPoint-4.log&filename=metaPoint-4.log`. 

It should be

`logging-console?filenameFilter=metaPoint-68.log&filename=metaPoint-68.log`

**Comment by jazdw** [comment]
@terrypacker it retrieves the log file name from this end point using the data source XID - `/rest/latest/meta-data-source/log-file-path/DS_XID`. If this is not correct, please re-open. PS this was not my handiwork.

**Comment by terrypacker** [comment]
@jazdw I will work this out with @pierpuccini, it was his handiwork anyway.

**Comment by terrypacker** [comment]
@pierpuccini the REST endpoint was misleading.  It expects you to supply the XID of the data point (not the data source).  This is the problem.  The endpoint is now working correctly but the UI needs fixed can you:

- [ ] Open the link in a new window (or allow that by right clicking)
- [ ] Use the data point XID in the REST request to build the link

**Comment by terrypacker** [comment]
@pierpuccini this issue is only relevant to Meta Data Points.

**Comment by jazdw** [comment]
I already fixed most of it up in the commit above, this commit changes it to use the data point XID.
infiniteautomation/ma-modules-private@40c74fae30b9082e80a3ee3b0521f802e883bffc
