### ISSUE TITLE
Permission Editor - Shows XIDs in some situations

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#362]
Have 3 roles that do exist I can see that in the "Other roles with access" view they display their XIDs and when displaying a newly added role without refreshing the page it displays the XID in the column in the table instead of the name.  This can be replicated by adding a new role while upgrading that is assigned to a permission on the item.  Here are some screenshots:

![image (5)](https://user-images.githubusercontent.com/3905204/96790507-9e7bd280-1392-11eb-94d4-3164569f1172.png)
![image (4)](https://user-images.githubusercontent.com/3905204/96790510-9facff80-1392-11eb-9e03-f5315d851417.png)
![image (3)](https://user-images.githubusercontent.com/3905204/96790516-a176c300-1392-11eb-8003-9bb2c264efa4.png)

**Comment by jazdw** [comment]
@terrypacker I have fixed up a couple of things around this but I am not sure what you mean in your steps to reproduce. Please test then close.

**Comment by terrypacker** [comment]
@jazdw looks good.  One last thing if you feel it is necessary.  If I have 2 tabs open, one on Excel Reports (or anywhere with the permissions component) and I modify the name of an existing role that is being displayed (used) on the other tab open to the roles page.  The name is not modified in the column for that role on the permissions component.  However it is updated in the (+ Other roles with access) area.  It seems this is all happening via web socket so I figure the displayed role should also be updated to read the other name.

Not a big deal but we are here and working on this so figured its worth looking at.

**Comment by jazdw** [comment]
@terrypacker I cannot reproduce the above, it updates in both places for me.

**Comment by jazdw** [comment]
Reproduced problem with Terry's help, two more commits
4f7e5658f25e4bd8130d3508be036786ba22f51c
f728a34475407ad9f24d845a0e0df22e6eff7556
