### ISSUE TITLE
Notify user of upgraded module / web app and give option to reload page

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#368]
Currently I think there are issues upgrading modules and the service worker cache ends up with cached files that are not compatible with each other.

**Comment by jazdw** [comment]
This is complete. See commits from 007da6c1a8f1039d2a154048cc26196cdc5ff21d to a6c53444e5964d380f9156eef5846300f4d8f905

When the new service worker is waiting to activate you will get the following notifications:
Toast message -
![image](https://user-images.githubusercontent.com/3579645/112394827-f2347400-8cc2-11eb-89b1-75608b39bfb2.png)
Toolbar button that appears -
![image](https://user-images.githubusercontent.com/3579645/112394875-04aead80-8cc3-11eb-9bc9-11745c138efa.png)
