### ISSUE TITLE
Edit Menu - cannot re-sort administration, help, examples, api docs

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#37]
If the administration of help items are dragged to a different position, they will stay there in the edit menu page but will almost always be displayed at the end of the list. Close as intentional?

**Comment by jazdw** [comment]
Yeah I know about this one, it was on my mental list of things to do. I added a weight parameter to each menu item, they are sorted by weight then array position now.

**Comment by jazdw** [comment]
The menu editor has been reworked and now sets the weight property correctly.
