### ISSUE TITLE
Event Handler Created with wrong referenceId2

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#374]
On the event handlers edit view on the event types tab if you select the upper checkbox for a data point event (may be others too) the referenceId2 field is sent as 0.  If you directly select the lower checkbox it works fine.

<img width="2102" alt="image" src="https://user-images.githubusercontent.com/3905204/106816621-bada0d00-6619-11eb-869f-572047a1554c.png">

**Comment by jazdw** [comment]
@terrypacker this is by design. You can choose for an event handler to handle all events for a data point or only a single detector.

**Comment by terrypacker** [comment]
@jazdw I don't think this is wired up to work that way in the backend is it?

**Comment by jazdw** [comment]
@terrypacker yes it should be. Re-open if not.

**Comment by terrypacker** [comment]
Yes it is wired up, here is the dao method that handles it:

https://github.com/infiniteautomation/ma-core-public/blob/07ba5f25bc75ee8e0700e655d1ff381d2a2cf5e1/Core/src/com/serotonin/m2m2/db/dao/EventHandlerDao.java#L170
