### ISSUE TITLE
Data Point Details - events table default sort & size

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#40]
Feel free to close as no, but I noticed the table doesn't have a default sort, and that it's default events per page is only 5.

I would consider sort on time descending (I think it's effectively ID ascending right now) and 15 or 25 rows per page

**Comment by jazdw** [comment]
@WillGeller can you look at this

**Comment by WillGeller** [comment]
I set the default limit to 15 and sort by descending timestamp (via 0475334216d03e635cabb73dc58170c27694dec3)
