### ISSUE TITLE
Events page - Acknowledge button gives bad count for emptied table

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#41]
Change the filter such that no events are in the table to be acknowledged, but the acknowledge button still says the same number it did a moment ago! Click it does not acknowledge the events, though.

**Comment by jazdw** [comment]
@WillGeller Can you look at this too please.

**Comment by WillGeller** [comment]
Fixed via 7c4c98e08d3489e559f76c39595988dc3726cfb7
