### ISSUE TITLE
Watch List Builder - Add the same point multiple times

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#43]
If one has an existing static watchlist, clicks the edit pencil, then on the watchlist settings tab moves from static to query or hierarchy and back to static, now when you advance to the second tab it is as though none of the points were added to the watchlist before, so adding them all will create doubles for any that were in the existing watchlist in the beginning.

**Comment by jazdw** [comment]
I can't replicate this one, works fine for me.
