### ISSUE TITLE
Edit menu - states and parents

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#45]
It seems an item's state determines what menus it opens, but it can explicitly set its menu parent to be displayed under. Was this a feature to have a certain menu item open a relevant but separate menu? Or might one of them be redundant?

It enables things like...
> A
  --> C
> B
  --> D

where clicking D opens A and closes B, or clicking C could close all. There is no way for both A and B to open both A and B

**Comment by jazdw** [comment]
It was designed this way so that states with a parent don't have to have be nested in folders, that is there is no one-to-one mapping between states and menu folders. The menu editor needs to be simplified and locked down as per my previous comment in #44
