### ISSUE TITLE
Custom Pages / Dashboard Designer - Save hotkey

### ISSUE THREAD

**Issue by WillGeller** [infiniteautomation/ma-dashboards#47]
Does the Dashboard Designer have the Ctrl+S to save feature. It doesn't seem to work with Cmd+S on Mac.

It would be nice to have the save hotkey working on both operating systems on both these pages

**Comment by jazdw** [comment]
No it doesn't, this would be a new feature.

**Comment by WillGeller** [comment]
Implemented on both pages via 1e0867a392a8afa17161135b8e1bc0e1fc954a9c
