### ISSUE TITLE
User Edit Page - Restore Editing User after re-login

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-dashboards#49]
I stopped Mango while editing a user, then restarted Mango and logged back in.  I was directed back to the edit users page for the user I was previously editing and the editing user was selected in the list but the inputs were all blank.

**Comment by jazdw** [comment]
I can't replicate this Terry, were you
* Logged in as admin?
* Editing your own user or another?
* Did you refresh the page at any point? Or did it automatically redirect you back to the login page when Mango started up then automatically back to the user edit page

**Comment by jazdw** [comment]
I've found some oddities with the page but not via the steps you outlined, looking into it.
