### ISSUE TITLE
Missing help pages

### ISSUE THREAD

**Issue by jazdw** [infiniteautomation/ma-dashboards#50]
Need some help pages for the following (will update as I find them)
* dashboard.help.users

**Comment by WillGeller** [comment]
Other pages that need help pages:

- [ ] Add Device
- [ ] Dashboard Designer
- [ ] Config Import/Export
- [ ] System Settings?

**Comment by WillGeller** [comment]
I added/updated help docs for the checked items in my previous comment. I probably won't get around to creating new ones for the last couple until I return to work but the ones that are new/updated could use a review and editing by another person ( @Puckfist ?)

**Comment by WillGeller** [comment]
I am starting to go back in today and update help pages, starting with the new toolbar UI on the page editor, file store etc...

**Comment by jazdw** [comment]
Outdated, new help system will be implemented.
