### ISSUE TITLE
DashboardDesigner - ma-scale-to outermost div

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#64]
If the ma-designer-root div has its element-specific property ma-scale-to set to Window, then when viewing that page the size of the div will be the window size, but there is also a header! This means I have to scroll to get to the bottom.

**Comment by jazdw** [comment]
By design, the scale-to window feature does precisely that, scales the div to the "window". It is primarily useful when the page fills the window, try giving the page a menu item with a state name that doesn't start with dashboards.
