### ISSUE TITLE
Deleting stuff, make people confirm

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#65]
This is moving this issue from ma-core-public to here, since it will be most applicable to the new data sources page, and perhaps elsewhere: https://github.com/infiniteautomation/ma-core-public/issues/203

Our discussion hinged around preventing users from deleting a data source or purging all data by simply clicking a button and a confirm.

**Comment by jazdw** [comment]
Closing as partially implemented, partially as too vague. Open new issues around specific buttons that need confirmation if still needed.
