### ISSUE TITLE
Data Point Details - Page loads with no Point Selected

### ISSUE THREAD

**Issue by WillGeller** [infiniteautomation/ma-dashboards#66]
On fresh installs of Mango or certain upgrades of Mango Modules, the point-list directive is not auto selecting the first data point in the system. Causes awkward blank cards:

![screen shot 2017-04-12 at 12 58 11 pm](https://cloud.githubusercontent.com/assets/6643010/24974716/6be6a700-1f80-11e7-9b4b-5ac46884ff6b.png)

**Comment by jazdw** [comment]
Same issue with dashboard designer, doesn't create a new page

**Comment by jazdw** [comment]
I've fixed the issue with the dashboard designer. I checked the data point details page and it is working fine now too so closing this issue.
