### ISSUE TITLE
Edit menu - Deeper nested state breaks built in pages

### ISSUE THREAD

**Issue by Puckfist** [infiniteautomation/ma-dashboards#68]
One doesn't have the option to put a custom menu item inside the Data Point Details page, but one can still do so through the state field! If I make my state ui.dataPointDetails.deeper and save the menu the item will nest into the Data Point Details item. Clicking on this menu item will only expand/collapse the menu item, not take me to the data point details page!

**Comment by jazdw** [comment]
No longer possible to do this, fix is in 0b07118612503c6e03d9caed2634bbc4f3cefdf6
