### ISSUE TITLE
UI Bug in Safari

### ISSUE THREAD

**Issue by WillGeller** [infiniteautomation/ma-dashboards#74]
new UI in safari and the home page doesn’t seem to be responsive?  It is fine in Chrome.
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/6643010/26632505/6a4e6d90-45de-11e7-820b-f3c8f4da77b0.png)

**Comment by WillGeller** [comment]
Seems to be a general issue with safari and the flex layout wrap stuff we use on many pages:
<img width="251" alt="screen shot 2017-05-31 at 9 01 28 am" src="https://cloud.githubusercontent.com/assets/6643010/26633130/59da01fc-45e0-11e7-8a10-a7adbcbc73c5.png">
<img width="550" alt="screen shot 2017-05-31 at 9 02 20 am" src="https://cloud.githubusercontent.com/assets/6643010/26633134/5daa5eb2-45e0-11e7-855a-f165ea27a7c3.png">
<img width="862" alt="screen shot 2017-05-31 at 9 02 48 am" src="https://cloud.githubusercontent.com/assets/6643010/26633140/60ec1336-45e0-11e7-9e68-35268d7a0308.png">
<img width="1054" alt="screen shot 2017-05-31 at 9 03 09 am" src="https://cloud.githubusercontent.com/assets/6643010/26633143/66e68d16-45e0-11e7-8a9d-dc8f32c955f0.png">
<img width="371" alt="screen shot 2017-05-31 at 9 03 49 am" src="https://cloud.githubusercontent.com/assets/6643010/26633152/6a4e4cbe-45e0-11e7-97c9-481d77019a48.png">
<img width="605" alt="screen shot 2017-05-31 at 9 04 08 am" src="https://cloud.githubusercontent.com/assets/6643010/26633155/6d4fae44-45e0-11e7-9ec9-bd44bf101ec8.png">

**Comment by WillGeller** [comment]
https://github.com/angular/material/issues/10516

Same issue even on official angular material docs

**Comment by jazdw** [comment]
This is a Safari bug, they haven't pulled in a fix from WebKit from the sounds of it. I dont think its worth our time trying to work around it.

**Comment by WillGeller** [comment]
I agree that it would be difficult to work around but we should be clear that basically the app runs best in chrome and may not work perfectly in other evergreen browsers.

Another issue with ignoring is it may cause problems with the mobile view on iPhones/iPads

**Comment by terrypacker** [comment]
I agree with Will its important for us to support iPhone/iPads.  Maybe dig a little deeper to see how big a deal this is or how soon they may pull in a fix?  I just updated my iPad yesterday and it doesn't work with the UI any better than Safari on OSX.

**Comment by jazdw** [comment]
@Joelhaggar and I just talked about this, we tried using the Chrome browser on iOS but no cigar, it uses Apple's rendering engine and is just as broken.

**Comment by WillGeller** [comment]
Many of our clients have to use the app on iPads/iPhones as a minimal requirement. I suggest we use the CSS override file mentioned above. It may be possible to detect if running on iOS or safari and load the CSS file conditionally to avoid downloading it on devices running chrome. Minifying the above file gets it down to 87k

**Comment by WillGeller** [comment]
Testing in Safari 10.0.3 Desktop it seems like the overrides CSS file is loading and is fixing a lot of the rendering issues I still see a few though.

Edit Menu Dialog doesn't display content:
<img width="847" alt="screen shot 2017-07-18 at 10 38 53 am" src="https://user-images.githubusercontent.com/6643010/28323117-e32d6b20-6ba5-11e7-850a-9e06ebeec6a0.png">

Users Page on Mobile, top dropdown cut off:
<img width="485" alt="screen shot 2017-07-18 at 10 44 11 am" src="https://user-images.githubusercontent.com/6643010/28323188-1836dc20-6ba6-11e7-8ccf-3d33d65db071.png">

**Comment by WillGeller** [comment]
Added a commit that fixed edit dialog rendering in Safari 6ddc2243648908c53369767ec7faa8fde2b3bd4f
