### ISSUE TITLE
Page Editor- Code Panel Dissapears

### ISSUE THREAD

**Issue by WillGeller** [infiniteautomation/ma-dashboards#80]
<img width="842" alt="screen shot 2017-06-16 at 1 53 57 pm" src="https://user-images.githubusercontent.com/6643010/27238556-5b34a972-529b-11e7-9e0b-549bb96fbe42.png">

This is on chrome at a medium width

**Comment by WillGeller** [comment]
Fixed via 876563396ebbefd0cce07cb1a31673ae9174c4ea looks like it was introduced in a layout fix for Firefox so I verified new fix works for both Chrome and Firefox

**Comment by jazdw** [comment]
@WillGeller thanks, I changed the default height to 400px and made the same change to the dashboard designer.
