### ISSUE TITLE
Users Page - Permissions Input auto checks

### ISSUE THREAD

**Issue by WillGeller** [infiniteautomation/ma-dashboards#82]
![screen shot 2017-06-26 at 10 28 48 am](https://user-images.githubusercontent.com/6643010/27544232-8014b7c0-5a5a-11e7-9000-4ef0cf40d194.png)

On the users page when you create a new user and then go to set permissions it has all of the permissions already checked when it should only have `user`

**Comment by jazdw** [comment]
Don't know how I missed that, thanks.
