### ISSUE TITLE
Directives from ngMap module are not namespaced

### ISSUE THREAD

**Issue by WillGeller** [infiniteautomation/ma-dashboards#88]
Note Issue on Inkscape SVG demo with <marker>

**Comment by jazdw** [comment]
Causes errors as a ngMap directive tries to apply to `<marker>` elements inside SVGs.

**Comment by WillGeller** [comment]
@jazdw What do you suggest for resolving this issue? Would it make sense to edit the source of the ngMap library to somehow to prevent this or is there some way to change the namespace to the directives included by it?

**Comment by jazdw** [comment]
ngMap library no longer used in Mango.
